### ISSUE TITLE
idle timer will not start before any action is created.

### ISSUE THREAD

**Issue by ryanbelt** [ReactTraining/react-idle#4]
idle time will not start counting after I refresh the page. Before I do any action on the page

**Comment by newyork-anthonyng** [comment]
@ryanbelt It looks like `react-idle` starts off as `idle` being true.

What behavior are you expecting, and what behavior are you seeing?

**Comment by ryanbelt** [comment]
```

**Comment by newyork-anthonyng** [comment]
@ryanbelt The `onChange` function only runs when the `idle` state has changed from `true` to `false`, or vice-versa.

In your example, the `idle` state after you refresh the page is `true`. The `console.log` does not print because it never changes `idle` state.

**Comment by ryanbelt** [comment]
Thank you @newyork-anthonyng . Problem solve. This could be close
